function batch_inundation

Nframes=481

modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0065/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0070/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0075/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0080/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0085/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0090/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0095/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0100/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0105/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0110/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0115/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0120/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0125/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0130/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0135/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0140/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0145/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0150/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0155/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0160/'
inundation(modelpath,Nframes)
modelpath='/Volumes/Kanagawa/Tohoku/HiResW_0165/'
inundation(modelpath,Nframes)